In [37]:
import numpy as np
import random
import pandas as pd
import math
from random import randint

In [38]:
def _readfile(file):

    # ----- read data -----
    df = pd.read_csv(file)
    df = df.fillna(method = 'ffill')

    # ----- Create Features -----
    X = df.drop(['id','class'], axis=1).copy(deep=False)
    X = (X-X.min())/(X.max()-X.min())

    # ----- Create Desired outputs -----
    Y = df[['class']].copy(deep=False)

    Input = X.to_numpy()
    Output = Y.to_numpy()

    return Input,Output

Input,Output = _readfile('./wdbc.csv')

In [39]:
def cross_var():
    index_list = list(range(len(Output)))
    random.shuffle(index_list)
    train_index = index_list[:512]
    test_index = index_list[512:]
    return train_index, test_index

In [56]:
def create_individul(Nueral_name, population):
    individul = []
    for i in range(population):

        pointR = 1
        temp0 = []
        while pointR <= (len(Nueral_name)-1):
            temp1 = []
            for j in range(Nueral_name[pointR]):
                temp2 = []
                for k in range(Nueral_name[pointR-1]):
                    temp2.append(random.randrange(-30000,30000)/10000) # [1,2,3]
                    temp2t = np.array(temp2)
                temp1.append(temp2t) # [[1,2,3],[1,2,3]]
                temp1t = np.array(temp1)
            temp0.append(temp1t)
            temp0t = np.array(temp0)    
            pointR = pointR + 1
        individul.append(temp0t)

    return np.array(individul)

<class 'numpy.ndarray'>


In [81]:

def feedforward(Nueral_name, individul, data_index):
    for i in data_index:
        pointlayer = 0
        while pointlayer < (len(Nueral_name)-1): #ทำทุกเลเยอร์
            temp = Input
            for j in range(Nueral_name[pointlayer+1]):
            # x = individul[pointlayer][j] * Input[data_index]

                # print(individul[pointlayer][j])
                print()
                print(Input[data_index])
                # print(individul[pointlayer][j] * Input[data_index])
            # print(pointlayer)
            pointlayer = pointlayer + 1

In [82]:
train_index, test_index = cross_var()
Nueral_name = [30,2,1]
individul = create_individul(Nueral_name, 1)
feedforward(Nueral_name, individul[0], test_index)


[[0.29764778 0.1707812  0.28297975 ... 0.34398625 0.09107037 0.04604486]
 [0.68999953 0.42881299 0.67866768 ... 0.76151203 0.0975754  0.10566706]
 [0.17364759 0.52451809 0.16736922 ... 0.21085911 0.363493   0.17335695]
 ...
 [0.20961711 0.17619209 0.20551448 ... 0.21635739 0.04849202 0.12613144]
 [0.21056368 0.19208657 0.2022666  ... 0.29127148 0.21900256 0.08271022]
 [0.05859246 0.37166047 0.06551033 ... 0.27075601 0.34634339 0.61366916]]

[[0.29764778 0.1707812  0.28297975 ... 0.34398625 0.09107037 0.04604486]
 [0.68999953 0.42881299 0.67866768 ... 0.76151203 0.0975754  0.10566706]
 [0.17364759 0.52451809 0.16736922 ... 0.21085911 0.363493   0.17335695]
 ...
 [0.20961711 0.17619209 0.20551448 ... 0.21635739 0.04849202 0.12613144]
 [0.21056368 0.19208657 0.2022666  ... 0.29127148 0.21900256 0.08271022]
 [0.05859246 0.37166047 0.06551033 ... 0.27075601 0.34634339 0.61366916]]

[[0.29764778 0.1707812  0.28297975 ... 0.34398625 0.09107037 0.04604486]
 [0.68999953 0.42881299 0.67866768 .

In [ ]:
# การทดลองที่ 1
Nueral_name = [30,8,1]
population = 1000
generation = 10

In [119]:
individul = create_individul([3,2,1],2)
# individul[ประชากรตัวที่][layer][เข้าโหนด]
print(individul[0])
print(individul[0][0])

[[[-2.0298, -2.7647, -1.9096], [-0.5734, 1.0689, -2.445]], [[-0.0494, 2.3297]]]
[[-2.0298, -2.7647, -1.9096], [-0.5734, 1.0689, -2.445]]


In [34]:
import numpy as np
a = [2,3]
a1 = np.array(a)
b = [4,5]
b = np.array(b)
print(a*b)

[ 8 15]
